//DOM CODES

// User Score Board DIV 
let user_div = document.createElement("div");
user_div.id = "user_score_div";
// Styling it
user_div.style.textAlign = "center";
user_div.style.fontWeight = "bold";
user_div.style.fontSize = "smaller";
//Div Content
user_div.innerHTML = '<h1>User!</h1>';                   
document.body.appendChild(user_div);

// Computer Score Board DIV
let pc_div = document.createElement("div");
pc_div.id = "pc_score_div";
// Styling it
pc_div.style.textAlign = "center";
pc_div.style.fontWeight = "bold";
pc_div.style.fontSize = "smaller";
//Div Content
pc_div.innerHTML = '<h1>Computer!</h1>';                   
document.body.appendChild(pc_div);
//Result Div
let result_div = document.createElement('div')
result_div.id = "result-div"
// Style
pc_div.style.textAlign = "center";
pc_div.style.fontWeight = "bold";
pc_div.style.fontSize = "smaller";
document.body.appendChild(result_div);

//footer
let footer = document.getElementById('footer')
footer.innerHTML = '<p>RPS Game Built By Abuzar Niazi On JavaScript With DOM & HTML CSS</p>';                   
document.body.appendChild(footer);
footer.style.textAlign = "center";
footer.style.fontWeight = "bold";
footer.style.marginTop = "100px"


//button logic
playerSelection = ""

let Rock = document.getElementById('rock')
let Paper = document.getElementById('paper')
let Scissors = document.getElementById('scissors')



// this code is generated by GPT which exits the code if my boolean makes the game finish, I was the one with the idea of boolean

//My understanding of how this code is working - It is wokring because it checks before executine playround if the gamefinished is true 


Rock.addEventListener("click", function () {
  if (gameFinished) {
    return; // Exit the function if the game is finished
  }
  playRound();
  playerSelection = "Rock";
});

Paper.addEventListener("click", function () {
  if (gameFinished) {
    return; // Exit the function if the game is finished
  }
  playRound();
  playerSelection = "Paper";
});

Scissors.addEventListener("click", function () {
  if (gameFinished) {
    return; // Exit the function if the game is finished
  }
  playRound();
  playerSelection = "Scissors";
});


// JS LOGIC 

let user_score = 0;
let pc_score = 0;
 
gameFinished = false

function playRound(){
   
    function getComputerChoice() {
    let choices = ["Rock", "Paper", "Scissors"]
    return choices[Math.floor(Math.random() * choices.length)]
  }
  const computerSelection = getComputerChoice()
  
  if (playerSelection === "Rock" && computerSelection === "Scissors"){
    user_score = ++user_score;
    user_div.textContent = 'Your Score is!' + user_score                               
    result_div.textContent = 'You chose ' + playerSelection +' And Computer chose ' + computerSelection
   } else if (playerSelection === "Scissors" && computerSelection === "Paper"){
    user_score = ++user_score;
    user_div.textContent = 'Your Score is!' + user_score                               
    result_div.textContent = 'You chose ' + playerSelection +' And Computer chose ' + computerSelection

  } else if (playerSelection === "Paper" && computerSelection === "Rock") {
    user_score = ++user_score;
    user_div.textContent = 'Your Score is!' + user_score                               
    result_div.textContent = 'You chose ' + playerSelection +' And Computer chose ' + computerSelection

  } else if (computerSelection === "Rock" && playerSelection === "Paper"){
  pc_score = ++pc_score;
  pc_div.textContent = 'Computer\s score is' + pc_score                               
  result_div.textContent = 'You chose ' + playerSelection +' And Computer chose ' + computerSelection

  } else if (computerSelection === "Scissors" && playerSelection === "Paper"){
  pc_score = ++pc_score;
  pc_div.textContent = 'Computer\s score is' + pc_score                               
  result_div.textContent = 'You chose ' + playerSelection +' And Computer chose ' + computerSelection

  }   else if (computerSelection === "Paper" && playerSelection === "Rock"){
  pc_score = ++pc_score;
  pc_div.textContent = 'Computer\s score is' + pc_score                               
  result_div.textContent = 'You chose ' + playerSelection +' And Computer chose ' + computerSelection

  } else if (playerSelection === "Rock" && computerSelection === "Rock"){
  result_div.textContent = 'It\'s a draw ! you both chose the same !'
  } else if (playerSelection === "Paper" && computerSelection === "Paper"){
    result_div.textContent = 'It\'s a draw ! you both chose the same !'
  } else if (playerSelection === "Scissors" && computerSelection === "Scissors"){
    result_div.textContent = 'It\'s a draw ! you both chose the same !'
  } else if (computerSelection === "Rock" && playerSelection === "Scissors"){
  pc_score = ++pc_score;
  pc_div.textContent = 'Computer\s score is' + pc_score                               

  } else {
  return "Error! Please enter a valid value! You chose " + playerSelection + " & Computer chose " + computerSelection;
  }
  
    if (user_score >=5 || pc_score >=5){
      gameFinished = true;
      if (user_score>pc_score) {
        result_div.textContent = "Congrats You Have Won This Round Against The Computer! Refresh to Play Again"
      } else {
        result_div.textContent = 'You lost this round. Computer Won! Refresh to Play Again'
      }
    }
 }
 

 
 
